# Generated by Django 3.2 on 2021-05-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quanlinhanvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhoahoc', models.CharField(max_length=50)),
                ('noidung', models.TextField()),
                ('loaikhoahoc', models.CharField(default='', max_length=50)),
                ('mota', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietKhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaybatdau', models.DateField()),
                ('ngayketthuc', models.DateField()),
                ('ghichu', models.TextField(default='')),
                ('khoahoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlidaotao.khoahoc')),
                ('nhanvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quanlinhanvien.nhanvien')),
            ],
        ),
    ]
