# Generated by Django 3.2 on 2021-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungdung', '0003_chucvu_nhanvienql_phongban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvienql',
            name='nam_kn',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
