# Generated by Django 3.2 on 2021-05-09 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ungdung', '0004_alter_nhanvienql_nam_kn'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvienql',
            name='chuc_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ungdung.chucvu'),
        ),
        migrations.AddField(
            model_name='nhanvienql',
            name='phong_ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ungdung.phongban'),
        ),
        migrations.AlterField(
            model_name='phongban',
            name='truongphong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
