# Generated by Django 3.2 on 2021-05-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quanlinhanvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bl', models.CharField(blank=True, max_length=50)),
                ('loai_bl', models.CharField(blank=True, max_length=50, null=True)),
                ('muc_pc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhuCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_pc', models.CharField(blank=True, max_length=50)),
                ('loai_pc', models.CharField(blank=True, max_length=50, null=True)),
                ('muc_pc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Thuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_t', models.CharField(blank=True, max_length=50)),
                ('loai_t', models.CharField(blank=True, max_length=50, null=True)),
                ('muc_t', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LuongCoBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luong', models.FloatField()),
                ('bac_luong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanliluongthuong.bacluong')),
                ('nhan_vien', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quanlinhanvien.nhanvien')),
                ('phu_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanliluongthuong.phucap')),
                ('thuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanliluongthuong.thuong')),
            ],
        ),
    ]
