# Generated by Django 3.2 on 2021-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanliluongthuong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacluong',
            old_name='muc_pc',
            new_name='muc_bl',
        ),
    ]
