# Generated by Django 3.2 on 2021-05-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ungdung', '0006_alter_chucvu_mo_ta'),
        ('quanlinhanvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenhopdong', models.CharField(max_length=50, null=True)),
                ('noidung', models.TextField()),
                ('mota', models.TextField(default='')),
                ('loaihopdong', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayki', models.DateField()),
                ('ngayketthuc', models.DateField()),
                ('hopdong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlituyendung.hopdong')),
                ('nhanvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlinhanvien.nhanvien')),
                ('quanli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ungdung.nhanvienql')),
            ],
        ),
    ]
