# Generated by Django 3.2 on 2021-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlituyendung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='loaihopdong',
        ),
        migrations.AddField(
            model_name='chitiethopdong',
            name='loaihopdong',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
