# Generated by Django 3.2 on 2021-05-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlinhanvien', '0001_initial'),
        ('ungdung', '0006_alter_chucvu_mo_ta'),
        ('quanlituyendung', '0002_auto_20210514_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoNhiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian', models.DateTimeField(auto_now_add=True)),
                ('ghichu', models.TextField(default='')),
                ('chucvumoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ungdung.chucvu')),
                ('nguoiduocbonhiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoiduocbn', to='quanlinhanvien.nhanvien')),
                ('nvbonhiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien', to='quanlinhanvien.nhanvien')),
            ],
        ),
    ]
