# Generated by Django 3.2 on 2021-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlituyendung', '0003_bonhiem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVienCu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennhanvien', models.CharField(max_length=50)),
                ('tenchucvu', models.CharField(max_length=50)),
                ('sodienthoai', models.CharField(max_length=50)),
                ('diachi', models.CharField(max_length=254)),
                ('lydothoiviec', models.TextField(default='')),
                ('ykiencanhan', models.TextField(default='')),
            ],
        ),
    ]
