# Generated by Django 3.2 on 2021-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlituyendung', '0005_nhanviencu_thoigiannghi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuyenDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(max_length=255)),
                ('thoigian', models.DateTimeField(auto_now_add=True)),
                ('chude', models.CharField(max_length=255)),
                ('noidung', models.TextField(default='')),
            ],
        ),
    ]
